config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  devise_for :customers
  root 'products#index'
  resources :categories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :cart_items
  before_destroy :not_referenced_by_any_cart_item

  private

   def not_referenced_by_any_cart_item
    unless cart_items.empty?
      errors.add(:base, 'cart items present')
      throw :abort
    end
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_customer!, :except => [ :show, :index ]
  #before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @categories = Category.all
    @cart_items = CartItem.all

    puts @categories
    puts params[:search]
      if params[:category_id].blank?
        if !params[:search].blank?
          puts"------------------"
          @products = Product.where(name: params[:search])
        else
          puts "------------home page"
          @products = Product.all
          @current_category = 'All'
        end
      else
        @products = Product.where(category_id: params[:category_id])
        @current_category = Category.find(params[:category_id]).name
      end

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @products = Product.where(category_id: params[:category_id])
  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!") and return
    else
      @parameter = params[:search].toLowerCase()
      @results = Product.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all

  end

  # GET /products/1/edit
  def edit

  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image_url, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<!--

<%= form_tag(root_path, :method => "get",
    class: 'form-inline my-2 my-lg-0') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control mr-sm-2" %>
    <div class="input-group-btn">
      <%= button_tag "search", :class => 'productsearchbutton',:name => nil%>
    </div>
  </div>
<% end %>
-->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<body class = "productbody">
	<div class ="container">
<p id="notice"><%= notice %></p>
<h1 class = "producttitle">Vow Me!</h1>
<%= render 'form', product: @product %>
<!--<% if not customer_signed_in? %>
	<%= link_to 'log in', new_customer_session_url %>
<% else %>
	<%= link_to 'log out', destroy_customer_session_url, method: :delete %>
<% end %>
<p><%= link_to 'View Cart' , cart_items_path %></p>

<% @categories.each do |category| %>
	<p><%= link_to category.name , category_path(category) %></p>
<% end %>
-->


<div class = "productpics">
    <% @products.each do |product| %>
      <td><%= link_to image_tag( product.image_url) , product_path(product) %></td>
    <% end %>
	<br>

</div>
</div>
</body>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<h3>Search Result</h3>

    <% @results.each do |result| %>
        <%= result.name %><br>
    <% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<body class = "productshowbody">
<div class = "container productshowtext">

<div class="card" style="width: 18rem;background-color: #F9F8EA;">
	<div class="card-header">
   <%= @product.name %>
  </div>
  <div class="card  mb-3" style="max-width: 18rem; background-color: #F9F8EA;">
	<img src="<%= image_url @product.image_url %>" class="card-img-top" alt="...">
<div class="card-body">

	 <p class="card-text"><strong>Description:</strong><%= @product.description %></p>
	 <p class="card-text"> <strong>Price:</strong>
  <%= @product.price %></p>
<%= form_with scope: :cart_item, url: cart_items_path, local: true do |form| %>




  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field" >

    <%= form.hidden_field :product_id, value:@product.id %>
  </div>

  <div class="actions cartsubmit">

 <%= form.submit %>

  </div>
<% end %>
</div>
</div>
</body>

<!--
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>



<p>
  <strong>Category:</strong>
  <% puts @product.category.inspect%>
  <%= @product.category.name %>
</p>
<p>
<%= image_tag(@product.image_url)%>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |-->